package com.beijing.ocean.multmediademo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.beijing.ocean.multmediademo.bean.User;
import com.beijing.ocean.multmediademo.bean.User0;

import com.beijing.ocean.multmediademo.greendao.UserDao;
import com.beijing.ocean.multmediademo.greendao.User0Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig user0DaoConfig;

    private final UserDao userDao;
    private final User0Dao user0Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        user0DaoConfig = daoConfigMap.get(User0Dao.class).clone();
        user0DaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        user0Dao = new User0Dao(user0DaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(User0.class, user0Dao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        user0DaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public User0Dao getUser0Dao() {
        return user0Dao;
    }

}
